TRUNCATE halls CASCADE;
TRUNCATE sessions CASCADE;
TRUNCATE customers CASCADE;
TRUNCATE tickets CASCADE;
TRUNCATE users CASCADE;

ALTER SEQUENCE halls_id_seq RESTART WITH 1;
ALTER SEQUENCE sessions_id_seq RESTART WITH 1;
ALTER SEQUENCE customers_id_seq RESTART WITH 1;
ALTER SEQUENCE tickets_id_seq RESTART WITH 1;
ALTER SEQUENCE users_id_seq RESTART WITH 1;